# Generated by Django 2.2 on 2019-04-11 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 12, 48, 31, 950869), null=True),
        ),
    ]
