# Generated by Django 2.2 on 2019-04-11 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190411_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 12, 56, 42, 294411), null=True),
        ),
    ]
