# Generated by Django 2.2 on 2019-04-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20190411_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
